# YouTube Music transcoding rules using ffmpeg
aac flc * *
	# IFRD:{RESAMPLE=-r %d}
	[ffmpeg] -loglevel quiet -i - -f flac -

aac mp3 * *
	# IFB:{BITRATE=-b:a %B}D:{RESAMPLE=-ar %D}
	[ffmpeg] -loglevel quiet -i - -f mp3 $BITRATE$ $RESAMPLE$ -

aac pcm * *
	# IF
	[ffmpeg] -loglevel quiet -i - -f s16le -
