# YouTube Music transcoding rules using ffmpeg
aac flc * *
	# IFRD:{RESAMPLE=-r %d}
	[ffmpeg] -loglevel quiet -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -i $URL$ -f flac -

aac mp3 * *
	# IFB:{BITRATE=-b:a %B}D:{RESAMPLE=-ar %D}
	[ffmpeg] -loglevel quiet -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -i $URL$ -f mp3 $BITRATE$ $RESAMPLE$ -

aac pcm * *
	# IF
	[ffmpeg] -loglevel quiet -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -i $URL$ -f s16le -
